//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceTip
    {
        public int maintId { get; set; }
        public Nullable<int> km { get; set; }
        public Nullable<int> carbrandId { get; set; }
        public string tip { get; set; }
    }
}
